### ISSUE TITLE
Finetuning on MacOS

### ISSUE THREAD

**Issue by adrvs** [bofenghuang/vigogne#15]
Hi, any idea if `finetune.py` should run on MacOS ? 

I tried the readme command
```
python finetune.py \
    --model_name_or_path name/or/path/to/hf/llama/7b/model \
    --train_file "data/vigogne_data_cleaned.json" \
    --output_dir "outputs/llama-7b-ft-vigogne-lora" \
    --run_name "llama-7b-ft-vigogne-lora" \
    --overwrite_output_dir \
    --model_max_length_percentile 95 \
    --preprocessing_num_workers 4 \
    --dataloader_num_workers 1 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --target_modules "q_proj" "v_proj" \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 8 \
    --num_train_epochs 3 \
    --learning_rate 3e-4 \
    --warmup_steps 100 \
    --logging_steps 25 \
    --save_strategy "steps" \
    --save_steps 200 \
    --save_total_limit 3 \
    --report_to "tensorboard" "wandb"
```

and got 
```
ValueError: FP16 Mixed precision training with AMP or APEX (`--fp16`) and FP16 half precision evaluation (`--fp16_full_eval`) can only be used on CUDA devices.
```

So I tried with `--use_mps_device` and `--fp16 0` but got
```Traceback (most recent call last):
  File "/Users/usr/PycharmProjects/vigogne/finetune.py", line 345, in <module>
    train()
  File "/Users/usr/PycharmProjects/vigogne/finetune.py", line 339, in train
    trainer.train()
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/transformers/trainer.py", line 1932, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/transformers/trainer.py", line 2727, in training_step
    loss = self.compute_loss(model, inputs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/transformers/trainer.py", line 2759, in compute_loss
    outputs = model(**inputs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/peft/peft_model.py", line 678, in forward
    return self.base_model(
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 570, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 566, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 293, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 197, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/peft/tuners/lora.py", line 698, in forward
    result = super().forward(x)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/bitsandbytes/nn/modules.py", line 320, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 500, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 293, in forward
    using_igemmlt = supports_igemmlt(A.device) and not state.force_no_igemmlt
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 226, in supports_igemmlt
    if torch.cuda.get_device_capability(device=device) < (7, 5):
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 381, in get_device_capability
    prop = get_device_properties(device)
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/Users/usr/PycharmProjects/vigogne/.venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by bofenghuang** [comment]
Hi @adrvs,

I have never run the training on M1.

But according to the last error message, you don't have enough memory to fit the model. You could try dispatching the model between CPU and GPU. See [here](https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu)
