### ISSUE TITLE
Erreur en lançant export_state_dict_checkpoint.py

### ISSUE THREAD

**Issue by Paloys** [bofenghuang/vigogne#25]
Bonjour,

En lançant le script export_state_dict_checkpoint.py avec la commande `python scripts/export_state_dict_checkpoint.py --base_model_name_or_path B:\LLaMA\llama-7b --lora_model_name_or_path bofenghuang/vigogne-falcon-7b-chat --output_dir ./models/7B_chat --base_model_size 7B`, tel que la [documentation](https://github.com/bofenghuang/vigogne/blob/main/vigogne/inference/README.md) le dit, j'ai cette erreur qui apparaît :
```
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\huggingface_hub\utils\_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/bofenghuang/vigogne-falcon-7b-chat/resolve/main/adapter_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\peft\utils\config.py", line 106, in from_pretrained
    config_file = hf_hub_download(pretrained_model_name_or_path, CONFIG_NAME, subfolder=subfolder)
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\huggingface_hub\file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\huggingface_hub\file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\huggingface_hub\utils\_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-64ac245d-5ce68a6424eb5e832f6390b8;06395a7c-91b2-4c4d-9f1b-8a0a0da7e524)

Entry Not Found for url: https://huggingface.co/bofenghuang/vigogne-falcon-7b-chat/resolve/main/adapter_config.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "B:\LLaMA\vigogne\scripts\export_state_dict_checkpoint.py", line 148, in <module>
    fire.Fire(main)
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "B:\LLaMA\vigogne\scripts\export_state_dict_checkpoint.py", line 42, in main
    lora_model = PeftModel.from_pretrained(
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\peft\peft_model.py", line 164, in from_pretrained
    PeftConfig.from_pretrained(model_id, subfolder=kwargs.get("subfolder", None)).peft_type
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\peft\utils\config.py", line 108, in from_pretrained
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'")
ValueError: Can't find 'adapter_config.json' at 'bofenghuang/vigogne-falcon-7b-chat'
```
En regardant l'url recherchée par le script, j'ai remarqué que le fichier `adapter_config.json` n'existait pas dans `bofenghuang/vigogne-falcon-7b-chat` ni dans `bofenghuang/vigogne-7b-instruct`.

J'ai essayé, comme indiqué dans l'issue #21, de retirer la ligne indiquée, mais cela na rien changé. Les poids de LLaMA que j'utilise sont ceux de huggyllama/llama-7b, mais a priori le problème ne vient pas de là...

Auriez-vous une solution ? Merci d'avance.

**Comment by bofenghuang** [comment]
Bonjour @Paloys ,

Merci pour avoir signalé le problème !.

La documentation est un peu obsolète. Je viens de la mettre à jour. Veuillez réessayer en vous référant à la nouvelle documentation :)

**Comment by bofenghuang** [comment]
Hi !

Le llama.cpp ne prend pas encore en charge les modèles basé sur Falcon ni notre script d'export. Pour le moment, vous pouvez uniquement utiliser les modèles basé sur LLaMA pour inférer avec llama.cpp.

Pour le modèle Falcon, vous pourriez consulter ce dépôt : https://github.com/cmp-nct/ggllm.cpp. Mais je n'ai pas encore eu l'occasion de l'essayer.

**Comment by Paloys** [comment]
Bonjour,

C'est noté, je vais essayer avec ce nouveau repo, merci pour votre aide !

Bonne journée.
